spring:
  application:
    name: notification-service
  profiles:
    active: dev
  config:
    import:
      - optional:file:.env[.properties]
      - "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  data:
    redis:
      host: localhost
      port: 5443
      password: systempass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

notification:
  cache:
    retry:
      max-attempts: 3
      delay-millis: 300