server:
  port: 8000

spring:
  application:
    name: saga-orchestrator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/saga_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.common.utils: WARN
    org.apache.kafka.common.network: WARN
    org.apache.kafka.clients.FetchSessionHandler: WARN
    org.apache.kafka.clients.Metadata: WARN
