server:
  port: 0

message: "payment-service default message"

spring:
  profiles:
    active: dev
  application:
    name: payment-service
  config:
    import:
      - optional:file:.env[.properties]
      - "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
