networks:
  ecommerce:
    external: true

services:
  user-db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    networks:
      - ecommerce

  product-db:
    image: postgres:17
    container_name: product-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    networks:
      - ecommerce

  product-read-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: product-read-db
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    ports:
      - "9200:9200"
    networks:
      - ecommerce

  stock-db:
    image: postgres:17
    container_name: stock-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stock_db
    ports:
      - "5434:5432"
    networks:
      - ecommerce

  order-db:
    image: postgres:17
    container_name: order-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    networks:
      - ecommerce

  brand-db:
    image: postgres:17
    container_name: brand-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: brand_db
    ports:
      - "5436:5432"
    networks:
      - ecommerce

  payment-db:
    image: postgres:17
    container_name: payment-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payment_db
    ports:
      - "5437:5432"
    networks:
      - ecommerce

  notification-db:
    image: postgres:17
    container_name: notification-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: notification_db
    ports:
      - "5438:5432"
    networks:
      - ecommerce

  coupon-db:
    image: postgres:17
    container_name: coupon-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: coupon_db
    ports:
      - "5439:5432"
    networks:
      - ecommerce

  review-db:
    image: postgres:17
    container_name: review-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: review_db
    ports:
      - "5440:5432"
    networks:
      - ecommerce

  cart-db:
    image: postgres:17
    container_name: cart-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cart_db
    ports:
      - "5441:5432"
    networks:
      - ecommerce

  saga-db:
    image: postgres:17
    container_name: saga-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: saga_db
    ports:
      - "5442:5432"
    networks:
      - ecommerce

  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack-compose
    restart: always
    environment:
      REDIS_ARGS: "--requirepass systempass"
    ports:
      - 5443:6379
      - 8001:8001
    networks:
      - ecommerce