server:
  port: 18080

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      password: systempass
      port: 5443
      timeout: 2000

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true  # Eureka 서버에 등록
    fetch-registry: true  # Eureka 서버로부터 레지스트리 정보 가져오기

user:
  admin:
    token: my-super-secret-admin-token

jwt:
  secretKey: XVFkQby3tnqMa8MUDANspAtarbl1VZyT
#  access-expiration-millis: 1800000 # 30분
  access-expiration-millis: 1209600000 # 14일
  refresh-expiration-millis: 1209600000 # 14일
  access-header-name: Authorization
  refresh-cookie-name: X-Refresh-Token
  header-prefix: Bearer
  access-subject: AccessToken
  refresh-subject: RefreshToken
  is-refresh-cookie-secure: false